import { AppLanguage } from "../middleware";

export const supportedLanguages = {
  [AppLanguage.English]: {
    code: AppLanguage.English,
    name: "English",
    shortName: "EN",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Arabic]: {
    code: AppLanguage.Arabic,
    name: "العربية",
    shortName: "عربي",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
  },
  [AppLanguage.Urdu]: {
    code: AppLanguage.Urdu,
    name: "پښتو",
    shortName: "پښتو",
    direction: "rtl",
    isLeftDirection: false,
  },
  [AppLanguage.Urdu]: {
    code: AppLanguage.Urdu,
    name: "اردو",
    shortName: "اردو",
    direction: "rtl",
    isLeftDirection: false,
  },
  [AppLanguage.Farsi]: {
    code: AppLanguage.Farsi,
    name: "فارسی",
    shortName: "فا",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
  },
  [AppLanguage.Chinese]: {
    code: AppLanguage.Chinese,
    name: "中文",
    shortName: "中",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Italian]: {
    code: AppLanguage.Italian,
    name: "Italiano",
    shortName: "IT",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Malaysia]: {
    code: AppLanguage.Malaysia,
    name: "Malaysia",
    shortName: "MY",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Hindi]: {
    code: AppLanguage.Hindi,
    name: "हिन्दी",
    shortName: "हि",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Indonasian]: {
    code: AppLanguage.Indonasian,
    name: "Bahasa Indonesia",
    shortName: "ID",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.French]: {
    code: AppLanguage.French,
    name: "Français",
    shortName: "FR",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Spanish]: {
    code: AppLanguage.Spanish,
    name: "Español",
    shortName: "ES",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Japanese]: {
    code: AppLanguage.Japanese,
    name: "日本語",
    shortName: "JP",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Vitenam]: {
    code: AppLanguage.Vitenam,
    name: "Tiếng Việt",
    shortName: "VI",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Philippines]: {
    code: AppLanguage.Philippines,
    name: "Tagalog",
    shortName: "tl-PH",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Urdu]: {
    code: AppLanguage.Urdu,
    name: "urdu",
    shortName: "ur",
    direction: "rtl",
    isLeftDirection: false,
    font: "font-kufi",
  },
  [AppLanguage.português]: {
    code: AppLanguage.português,
    name: "port",
    shortName: "pt-PT",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Thailand]: {
    code: AppLanguage.Thailand,
    name: "thail",
    shortName: "th-TH",
    direction: "ltr",
    isLeftDirection: true,
  },
  [AppLanguage.Chinese_Traditional]: {
    code: AppLanguage.Chinese_Traditional,
    name: "chinese",
    shortName: "zh-TW",
    direction: "ltr",
    isLeftDirection: true,
  },
};
